// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dabrelCMS.data;

#nullable disable

namespace dabrelCMS.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20260515030822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("dabrelCMS.models.CMSBlock", b =>
                {
                    b.Property<Guid>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title2")
                        .HasColumnType("TEXT");

                    b.HasKey("BlockId");

                    b.ToTable("CMSBlocks");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("CMSFiles");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CMSBlockBlockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shortcut")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title2")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CMSBlockBlockId");

                    b.ToTable("CMSItems");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSPage", b =>
                {
                    b.Property<Guid>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CMSSiteSiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("NavTitle")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shortcut")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("INTEGER");

                    b.HasKey("PageId");

                    b.HasIndex("CMSSiteSiteId");

                    b.ToTable("CMSPages");

                    b.HasData(
                        new
                        {
                            PageId = new Guid("00000000-0000-7000-8000-000000000004"),
                            HeroImage = "",
                            NavTitle = "Home",
                            Shortcut = "",
                            SiteId = new Guid("00000000-0000-7000-8000-000000000001"),
                            Sort = 1,
                            Summary = "Page summary goes here",
                            Tags = "home",
                            Title = "Welcome",
                            isHidden = false,
                            isOn = true,
                            isPrivate = false
                        });
                });

            modelBuilder.Entity("dabrelCMS.models.CMSPageBlock", b =>
                {
                    b.Property<Guid>("PageBlockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltTitle")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CMSPagePageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.HasKey("PageBlockID");

                    b.HasIndex("CMSPagePageId");

                    b.ToTable("CMSPageBlocks");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSSite", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyBottom")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTop")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Design")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Footer1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Footer2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Footer3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Footer4")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnAllPages")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId");

                    b.ToTable("CMSSites");

                    b.HasData(
                        new
                        {
                            SiteId = new Guid("00000000-0000-7000-8000-000000000001"),
                            BodyBottom = "",
                            BodyTop = "",
                            Created = new DateTime(2025, 1, 1, 0, 1, 0, 0, DateTimeKind.Unspecified),
                            Design = "mountain",
                            FaviconUrl = "",
                            Footer1 = "footer 1",
                            Footer2 = "",
                            Footer3 = "",
                            Footer4 = "",
                            ImageFileName = "",
                            MetaDescription = "Description",
                            MetaImagePath = "",
                            Name = "test",
                            OnAllPages = "",
                            SubTitle = "subtitle",
                            Title = "title"
                        });
                });

            modelBuilder.Entity("dabrelCMS.models.CMSSiteUrl", b =>
                {
                    b.Property<Guid>("SiteUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CMSSiteSiteId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Primary")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SiteUrlId");

                    b.HasIndex("CMSSiteSiteId");

                    b.ToTable("CMSSiteUrls");

                    b.HasData(
                        new
                        {
                            SiteUrlId = new Guid("00000000-0000-7000-8000-000000000002"),
                            Primary = true,
                            SiteId = new Guid("00000000-0000-7000-8000-000000000001"),
                            Url = "localhost"
                        });
                });

            modelBuilder.Entity("dabrelCMS.models.CMSUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Salt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("CMSUsers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-7000-8000-000000000003"),
                            Email = "test@dabrel.com",
                            FirstName = "test",
                            LastName = "user",
                            Mobile = "",
                            NameIdentifier = "",
                            Password = "test",
                            Provider = "Cookies",
                            Roles = "admin",
                            Salt = 0,
                            SiteId = new Guid("00000000-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("dabrelCMS.models.CMSItem", b =>
                {
                    b.HasOne("dabrelCMS.models.CMSBlock", null)
                        .WithMany("cmsItems")
                        .HasForeignKey("CMSBlockBlockId");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSPage", b =>
                {
                    b.HasOne("dabrelCMS.models.CMSSite", null)
                        .WithMany("cmsPages")
                        .HasForeignKey("CMSSiteSiteId");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSPageBlock", b =>
                {
                    b.HasOne("dabrelCMS.models.CMSPage", null)
                        .WithMany("pageBlocks")
                        .HasForeignKey("CMSPagePageId");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSSiteUrl", b =>
                {
                    b.HasOne("dabrelCMS.models.CMSSite", null)
                        .WithMany("cmsSiteUrls")
                        .HasForeignKey("CMSSiteSiteId");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSBlock", b =>
                {
                    b.Navigation("cmsItems");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSPage", b =>
                {
                    b.Navigation("pageBlocks");
                });

            modelBuilder.Entity("dabrelCMS.models.CMSSite", b =>
                {
                    b.Navigation("cmsPages");

                    b.Navigation("cmsSiteUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
